#! usr/bin/env node 
import inquirer from "inquirer";
const guessOfTheUser = await inquirer.prompt([
    {
        message: "Enter Your Guess For The Predicted Number Generated by the Computer(1-10)", type: "number", name: "guessedNummber"
    },
]);
let randomNumber = Math.round((Math.random() * 10) + 1);
if (guessOfTheUser.guessedNummber === randomNumber) {
    console.log("You have won the game! Congratulations!");
}
else {
    console.log("Please TryAgain Later!");
}
console.log("The correct number was:", randomNumber);
